### ISSUE TITLE
New AMP gallery skips an image for every left swipe

### ISSUE THREAD

**Issue by HazemAM** [android-police/androidpolice-public#100]
The new AMP gallery advances by 2 images instead of 1 when swiped left fast enough (it doesn't happen when swiped slowly or when swiping to the right).

#### Expected behavior
When swiped left, the gallery should always advance by one image.

#### Actual behavior
The gallery advances by two images sometimes.

#### Steps to reproduce the problem
In an AMP gallery, swipe left with moderate speed (not slow but not necessarily fast).

#### Demo
![android-police-amp-galley-bug](https://user-images.githubusercontent.com/3602800/64003173-fe1e7b00-cb0b-11e9-9f4f-4e158abfd640.gif)

**Comment by archon810** [comment]
Thanks for the report. We got several other reports about this, so we'll be digging into it ASAP. It could be a bug in AMP galleries, so we'll see, and if it is, we'll report it upstream.

**Comment by archon810** [comment]
Other buggy urls reported:

https://www.androidpolice.com/2018/08/18/find-recently-uploaded-pics-google-photos-even-date-back-many-years/?amp

https://www.androidpolice.com/2019/08/29/xiaomi-release-redmi-note-8-pro-64mp-camera/?amp

**Comment by archon810** [comment]
The bugs seems to be in AMP itself, sadly. Please see the links above. I'm not sure what else we can do to fix until they do.

**Comment by HazemAM** [comment]
Yeah it's definitely an AMP issue judging from these issues you linked. The ampproject/amphtml#21559 one is what we are looking for. Apparently it was bumped up in priority last June, so at least it has some attention.

Hopefully it gets fixed soon, but I guess if we want it fixed faster someone has to contribute to the [amphtml](https://github.com/ampproject/amphtml) repo. This is definitely the directory we should be looking at: [/extensions/amp-carousel](https://github.com/ampproject/amphtml/tree/master/extensions/amp-carousel).

**Comment by archon810** [comment]
The AMP team has a solution, but it'll take a few weeks:

https://github.com/ampproject/amphtml/issues/22608#issuecomment-526724288

https://github.com/ampproject/amphtml/issues/21559#issuecomment-526724190

**Comment by HazemAM** [comment]
Oh that's great to hear, looking forward to that.

**Comment by archon810** [comment]
Asked the AMP team twice for updates to the tickets, but nothing so far.

**Comment by HazemAM** [comment]
The problem is that the fix is already implemented, but they wouldn't merge it for some reason.
So even if we wanted to help we wouldn't be able to.

**Comment by archon810** [comment]
Carousel 0.2 is now out and both issues reported above are fixed.
