### ISSUE TITLE
Weird issue with AMP gallery

### ISSUE THREAD

**Issue by smiller171** [android-police/androidpolice-public#103]
Looks like the gallery is loading the wrong size on AMP pages.

Pixel 3, Android Q, Chrome Beta 77

![Wrong size Gallery](https://i.imgur.com/ExmMuzC.png)

**Comment by archon810** [comment]
Thank you for the report. This is not the gallery, if I understand correctly, but rather a GFYCAT embed of the gallery demo showing way too wide on AMP. We've spotted the issue and updated the article, but then ran into the cache not updating, hence you not seeing the fix.

We're going to resolve both issues. I'll keep this ticket open until GFYCAT embeds are sized properly.

**Comment by archon810** [comment]
The gfycat sizing issue has been resolved.
