### ISSUE TITLE
Comment Count 0 (AMP page)

### ISSUE THREAD

**Issue by bzier** [android-police/androidpolice-public#104]
#### Expected behavior
The comments count at the top of the page should show the number of comments on the article.
![Screenshot_20190831-204031~2](https://user-images.githubusercontent.com/714528/64071508-8d24b380-cc30-11e9-966d-f2ed35328eee.png)

#### Actual behavior
The comments count is showing 0.
![Screenshot_20190831-203920~2](https://user-images.githubusercontent.com/714528/64071510-96158500-cc30-11e9-860e-6e7eb4d81f22.png)

#### Steps to reproduce the problem
Visit the article [here](https://www-androidpolice-com.cdn.ampproject.org/v/s/www.androidpolice.com/2019/08/31/android-police-now-supports-google-amp/?amp_js_v=a2&amp_gsa=1&amp) and see 0 comments. Visit the same non-amp article [here](https://www.androidpolice.com/2019/08/31/android-police-now-supports-google-amp/) and see more than 0 comments.

**Comment by archon810** [comment]
Thank you for the report. Looks like it's related to cached content not updating, which we're trying to resolve.

**Comment by archon810** [comment]
We pinged Disqus about an official method of showing live up-to-date comment counts on AMP, but they didn't have a solution.

We'll try to cook something up ourselves, and in the meantime can only rely on the AMP CDN caches getting updated. However, they don't update very frequently, so we're hoping our solution will work.

**Comment by archon810** [comment]
This was resolved via our custom method that uses `amp-list` a few weeks ago, forgot to close this ticket.

We also told Disqus how to do this here https://github.com/disqus/disqus-install-examples/issues/38, but they haven't replied.
