### ISSUE TITLE
X new articles no longer has options

### ISSUE THREAD

**Issue by Madis0** [android-police/androidpolice-public#105]
#### Expected behavior
The "X new articles" panel should have the options of selecting between 12/24/72 hours and new/popular/comments sort options.

#### Actual behavior
The options are gone and the top section of the panel is just white. 

#### Steps to reproduce the problem

1. Click on "X new articles" 
2. Look for the options 

![](https://i.imgur.com/5A5cnb1.png)

**Comment by archon810** [comment]
Thank you for the report. This looks like a regression following AMP or another recent push.

**Comment by archon810** [comment]
This issue is resolved.
