### ISSUE TITLE
No tweets on amp site

### ISSUE THREAD

**Issue by d0x360** [android-police/androidpolice-public#106]
#### Expected behavior
Page to load everything normal page does

#### Actual behavior
In the amp version the tweets didnt show up (on the article about the new amp site)  but they do on

https://www.androidpolice.com/2019/08/31/android-police-now-supports-google-amp/
 
the non amp version###

### Steps to reproduce the problem
Load the page

**Comment by archon810** [comment]
I'm assuming you're not actually talking about https://www.androidpolice.com/2019/08/31/android-police-now-supports-google-amp/?amp, but rather the Google AMP CDN version - something like https://www-androidpolice-com.cdn.ampproject.org/v/s/www.androidpolice.com/2019/08/31/android-police-now-supports-google-amp/?amp=&amp_js_v=0.1.

We've updated our version, but the Google AMP CDN one is still cached and didn't update.

The reason for that is currently pushing updates to AMP caches is broken. We're working on it, but we have to wait for Google to fix something. Once we figure it out, the caches should update... hopefully.

https://github.com/ampproject/amphtml/issues/24326

**Comment by d0x360** [comment]
Yeah the version I got was from a url in Google now's news feed.

I didn't try loading the amp site directly from Android police.

**Comment by archon810** [comment]
We've sorted out AMP CDN cache updates... for the most part. It's still not perfect, and the ticket referenced above will track the progress there, plus another ticket here https://github.com/W3EDGE/w3-total-cache/issues/34.
