### ISSUE TITLE
AMP zoom issue on iOS

### ISSUE THREAD

**Issue by ChrisBegley** [android-police/androidpolice-public#107]
First off, GREAT job with the new AMP implementation. 

I did notice a small issue that I believe is iOS specific. When you tap to type into the search field at the top of an AMP page on iOS, it zooms in the page. I believe this is because iOS automatically zooms in on input fields if their font size is less than 16px. If you set the search field to be 16px or greater, it _should_ resolve the issue.

**Comment by archon810** [comment]
Thank you, @ChrisBegley.

I believe we resolved this on the non-AMP site recently, so we should be able to apply the same fix here.

**Comment by archon810** [comment]
This fix for this issue has been rolled out (though you may see some cached data, especially in AMP caches).

Example url: https://www.androidpolice.com/2019/09/03/android-website-updated-for-android-10/?amp&nocache=1.
