### ISSUE TITLE
Most images are not working

### ISSUE THREAD

**Issue by joshuanoyce** [android-police/androidpolice-public#108]
#### Expected behavior
To see images along with the article.

#### Actual behavior
Most of the images in the artfile I read about Android Authority switching to Google amp did not show up. Instead they just showed an error message. 

#### Steps to reproduce the problem
Was using Android 7 with latest version of the Google search App

**Comment by archon810** [comment]
Screenshots please?

**Comment by archon810** [comment]
I'll reopen if there's a credible bug report to update with here.

**Comment by joshuanoyce** [comment]
Sorry just saw your messages. It was fixed as of 5pm mst today. 

Sent from my iPhone
Joshua
