### ISSUE TITLE
bottom banner ad position

### ISSUE THREAD

**Issue by devVansh** [android-police/androidpolice-public#110]
[####]
![Screenshot (1)](https://user-images.githubusercontent.com/48434197/65945040-ac417b80-e450-11e9-9673-3e45cee3f9c5.png)
 Expected behavior
banner ad should be at bottom

#### Actual behavior
when footer is shown banner add positioned at middle of footer

**Comment by archon810** [comment]
Thanks for reporting this. I'm furious about this and noticed it earlier today.

Our "ad partner" Sortable, which is now getting shitcanned after these shenanigans, decided to add a sticky banner to the site without telling us, and I'm in the process of removing what's left of their code now. Such a dick move, I couldn't believe it.

**Comment by archon810** [comment]
It's going to take me a little while to properly disable Sortable units, but in the meantime, we hid it with CSS as a quick workaround.

**Comment by archon810** [comment]
They replied and disabled the unit. https://twitter.com/Sortable/status/1179046786117361664

I'm going to close this.

**Comment by devVansh** [comment]
Great, thank you
Loved your site and blogs
