### ISSUE TITLE
Ad with Scroll enabled.

### ISSUE THREAD

**Issue by sircod** [android-police/androidpolice-public#112]
#### Expected behavior
Should be no ads when Scroll is active.

#### Actual behavior
Getting an ad (for Banggood) just above the comments.
![image](https://user-images.githubusercontent.com/2597002/74065321-733e8800-49a9-11ea-8a10-93a99d236392.png)

#### Steps to reproduce the problem
This is using Brave browser with shields disabled on Windows 10. Doesn't load the ad every time, sometimes takes a couple refreshes.

**Comment by archon810** [comment]
This is the only ad we aren't currently able to disable, and it's coming from Disqus (it's an iframe so we can't control what shows in it).

We've gotten in touch with Disqus, gave them all the details about Scroll, and are currently waiting to see if they take action or provide us with a parameter to pass to the iframe when a Scroll user is detected.

**Comment by msfjarvis** [comment]
In my case the usual ad spots are replaced with ads asking me to sign up on Scroll, which I already have. Is this intended?

**Comment by archon810** [comment]
@msfjarvis Do you still have the ad blocker on? Those are house ads that are run on ad blocked locations.

We can probably detect Scroll here and disable those in case it'd active, but in the meantime disabling the ad blocker should do the trick.

**Comment by msfjarvis** [comment]
> @msfjarvis Do you still have the ad blocker on? Those are house ads that are run on ad blocked locations.

That was it! I had to disable both uBlock and [Privacy Badger](https://privacybadger.org/) though.

**Comment by tmzullinger** [comment]
I'm not sure if this should be a a separate ticket or not. Happy to file it as such if you'd prefer it that way.

I'm also using Scroll and twice in the past few days I've had full page ads displayed when following a link from the site home page to an article.

This is on a Pixel 2XL running Chrome stable. I've got no ad blocker in place for Chrome (nor any external blocker like Pi-Hole).

![Screenshot_20201014-140229](https://user-images.githubusercontent.com/806319/96028080-d6c96100-0e26-11eb-836c-ec8b243cd251.png)

The ad content was different the previous time, but still a full page. I didn't capture it, as I thought it was a one-off bug not worth mentioning.

Thanks for all the great work on Android Police!

**Comment by tmzullinger** [comment]
This happened twice more today. Attached are screenshots with times of the occurrences (EDT, as before).

![Screenshot_20201014-151232](https://user-images.githubusercontent.com/806319/96049644-531f6c80-0e46-11eb-8c3d-d6e4a5f906e3.png)
![Screenshot_20201014-175126](https://user-images.githubusercontent.com/806319/96049646-53b80300-0e46-11eb-8ce5-528df31f6de7.png)

The second one was when following a link from the home page to https://www.androidpolice.com/2020/10/14/youtube-music-now-lets-free-users-download-playlists-containing-uploaded-songs/. I didn't note where the first was - it from the home page though.

I hope you can find the source of this and send the dirtbags packing. They deserve far less than nothing.

**Comment by tmzullinger** [comment]
I tested from a new Pixel 4a that's only been lightly used, to help ensure it wasn't something on my other device. Same issue there.

I did finally think to note the URL of the ad screen too, sorry for not including that before.

From the home page, clicking on the article at https://www.androidpolice.com/2020/10/14/youtube-music-now-lets-free-users-download-playlists-containing-uploaded-songs/, I was directed to https://www.androidpolice.com/#google_vignette first (a full page add for the Pixel 5). I'll skip the ad attachment for now, presuming that too many screenshots aren't useful. Let me know if there's anything else I should be including.

**Comment by archon810** [comment]
Thanks for reporting these @tmzullinger. I've been trying to figure out wtf is suddenly going on and then found this. Damnit, Google:

![Screenshot 2020-10-15 at 8 54 03 AM](https://user-images.githubusercontent.com/469543/96156336-ce743300-0ec5-11eb-86f2-3ee841582b5d.png)
![Screenshot 2020-10-15 at 8 53 13 AM](https://user-images.githubusercontent.com/469543/96156343-cf0cc980-0ec5-11eb-9eeb-9a90b7d29df9.png)
![Screenshot 2020-10-15 at 8 52 48 AM](https://user-images.githubusercontent.com/469543/96156346-cf0cc980-0ec5-11eb-9944-a11a68bd60dd.png)

I've now concluded this auto experiment and kept the original options of showing no autoads (which is what these interstitial/vignette ads are).

**Comment by archon810** [comment]
We have worked with Scroll and Disqus, and I'm happy to report that Scroll users will no longer see Disqus ads as of today. \o/
