### ISSUE TITLE
Broken page selector color

### ISSUE THREAD

**Issue by MEPoss** [android-police/androidpolice-public#113]
#### Expected behavior
The selected page color in the page selector at the bottom of the website should be different from the other pages

#### Actual behavior
All pages numbers are of the same color

#### Steps to reproduce the problem
Scroll down to the page selector, select a page and scroll down again
![AP_Page-Selector-Color-Bug](https://user-images.githubusercontent.com/29541560/74273741-378d2080-4d11-11ea-9287-82c795f568c4.jpg)

**Comment by archon810** [comment]
Thanks for the report, I can confirm this bug. We'll get it fixed up!

**Comment by archon810** [comment]
The fix is out.
