### ISSUE TITLE
Text within code snips is not consistently themeing

### ISSUE THREAD

**Issue by ngaustad** [android-police/androidpolice-public#114]
#### Expected behavior
Black text should be white

#### Actual behavior
Black text is still black

#### Steps to reproduce the problem
View a page that has code snips, ex: https://www.androidpolice.com/2020/02/14/gmail-inbox-bundles-labels-apk-teardown/
![image](https://user-images.githubusercontent.com/36749102/74577236-098f2280-4f43-11ea-801a-f250a626fa41.png)

**Comment by archon810** [comment]
Thanks, we already spotted this today as well and will be fixing shortly.

**Comment by archon810** [comment]
We have rolled out the fix:

![image](https://user-images.githubusercontent.com/469543/75277913-c5f7ac80-57bd-11ea-874d-c2bd75965145.png)

![image](https://user-images.githubusercontent.com/469543/75277931-cdb75100-57bd-11ea-867e-fe7da4a46065.png)
