### ISSUE TITLE
Selected text colour in dark theme

### ISSUE THREAD

**Issue by nerdbloke** [android-police/androidpolice-public#115]
#### Expected behaviour
Selected text should provide high contrast to non-selected text.

#### Actual behaviour
Black background instead of dark grey, white text instead of off-white.

#### Steps to reproduce the problem
Set dark theme, select text; contrast is not high.

![selected](https://user-images.githubusercontent.com/61119505/74609450-ecdd2100-50e1-11ea-9eeb-34664ef5d44e.png)

**Comment by archon810** [comment]
Thanks for your report, we'll try to fix this if possible.

**Comment by archon810** [comment]
We have fixed the issue:

![image](https://user-images.githubusercontent.com/469543/74777955-72321400-524f-11ea-83de-52cb8aaf8ff2.png)
