### ISSUE TITLE
Embedded Reddit post dark mode compatibility

### ISSUE THREAD

**Issue by MeUnderTest** [android-police/androidpolice-public#116]
#### Expected behavior

Embedded post readay in dark mode

#### Actual behavior

Embedded post not readable

#### Steps to reproduce the problem
![Screenshot_20200217-011922](https://user-images.githubusercontent.com/53955577/74614809-f12a2e00-5123-11ea-85ae-abad74a0315f.jpg)

**Comment by archon810** [comment]
We're working on a fix that would work better on both dark and regular themes. Sadly, Reddit doesn't adjust properly on its own.

**Comment by archon810** [comment]
We're unable to modify the font color, and the embeds are transparent, so the only way we can fix it is by using a background color when in dark mode. Which is what we've done:
![image](https://user-images.githubusercontent.com/469543/74778463-7d397400-5250-11ea-8af4-ea1c78e7d344.png)
