### ISSUE TITLE
Appdetails rating style

### ISSUE THREAD

**Issue by DawEdhel** [android-police/androidpolice-public#117]
#### Expected behavior

Classic star rating being white.

#### Actual behavior

Currently it's grey/black.

#### Steps to reproduce the problem

Any post with appdetails container.
![Annotation 2020-02-17 174801](https://user-images.githubusercontent.com/15185758/74664162-3f840f00-51ae-11ea-8208-a710d4f28f15.png)

**Comment by archon810** [comment]
We'll tweak this.

**Comment by archon810** [comment]
We have rolled out the fix:

![image](https://user-images.githubusercontent.com/469543/75277856-ad879200-57bd-11ea-840d-9eabb751f94d.png)
