### ISSUE TITLE
Feed not working since March 1st

### ISSUE THREAD

**Issue by Pa9an** [android-police/androidpolice-public#118]
#### Expected behavior
Feed updating according to news
https://www.androidpolice.com/feed

#### Actual behavior
Feed stopped updating

#### Steps to reproduce the problem
Open mentined link...last news is from March 1st

**Comment by archon810** [comment]
The feed is working for us and it is also used for posting new posts to our social media accounts as well as Pushbullet, which are all working.

Could you please post the raw content you're seeing that is allegedly stale to a gist and link it here?

**Comment by Pa9an** [comment]
I am using LiveMarks add-in for Firefox (Win 10).
Clearing the browsing cache suddenly fixed this for me now...sorry for the alert :-/
Issue can be closed.
