### ISSUE TITLE
Images fail to load due to native lazy-loading after M83 update (M84, M85 also affected)

### ISSUE THREAD

**Issue by archon810** [android-police/androidpolice-public#119]
#### Expected behavior
Images should load.

#### Actual behavior
Images don't load.

#### Steps to reproduce the problem
(1) Load https://www.androidpolice.com/ on Chrome for Android M83+
(2) Observe that hero images are not showing up. These images use loading="lazy" and have worked in M81 and before.

![Screenshot_20200523-105725](https://user-images.githubusercontent.com/469543/82737493-31cab200-9ce6-11ea-86c7-28fea6a1ce4a.jpg)

I've opened a ticket https://bugs.chromium.org/p/chromium/issues/detail?id=1085947 as well as pinged a few people on Twitter https://twitter.com/ArtemR/status/1264254302383554560.

**Comment by addyosmani** [comment]
From the Chrome side, I'll respond as we dig into this on the above ticket. I've verified the behavior you're seeing is reproducible across the last three Chrome channels. IIRC, the main loading=lazy changes we've been experimenting with are tweaking the threshold values.

For the time being, I may suggest changing these to loading=eager if it's heavily impacting production traffic.

**Comment by archon810** [comment]
@addyosmani Yeah, I was going to remove the lazy for now but wanted to leave it in there long enough for you guys to reproduce and root cause. Do you have a test case saved offline so that we can proceed with this now or do you need more time?

**Comment by archon810** [comment]
The issue was root caused and fixed here https://bugs.chromium.org/p/chromium/issues/detail?id=1085947#c35.

Awaiting further information on the release of the fixed Chrome version.

**Comment by archon810** [comment]
We pushed a fix on our end as Chrome is unlikely to fix it, or at least any time soon.
