### ISSUE TITLE
RSS feed broken

### ISSUE THREAD

**Issue by ggroom** [android-police/androidpolice-public#122]
The feed from https://www.androidpolice.com/feed seems to have stopped on the 16th of July; attempts to fetch result in an HTTP error (503).

![Screenshot_20200724_104151](https://user-images.githubusercontent.com/3595060/88353629-6cf86880-cd9d-11ea-9e8d-9940779444b3.png)

![Screenshot_20200724_104240](https://user-images.githubusercontent.com/3595060/88353632-6e299580-cd9d-11ea-96be-ef7651efd2db.png)

**Comment by archon810** [comment]
Hi,

The feed works, but we're now blocking a lot of bot traffic from hosting companies with high abuse rates.

What tool are you using?

**Comment by ggroom** [comment]
> Hi,
> 
> The feed works, but we're now blocking a lot of bot traffic from hosting companies with high abuse rates.
> 
> What tool are you using?

I'm using Newsblur (https://newsblur.com)

**Comment by archon810** [comment]
Thanks, I'll look into it.

**Comment by ggroom** [comment]
> Thanks, I'll look into it.

Thanks, I appreciate it.

**Comment by archon810** [comment]
Give it a go now and please reopen if it's not fixed.

**Comment by 1nikolas** [comment]
Feedly doesn't show images

![Monosnap 2020-07-27 1 AM-58-49](https://user-images.githubusercontent.com/30593419/88491629-d1d5dd80-cfac-11ea-956a-55fb109537b4.png)

**Comment by slavakraynov** [comment]
I'm using a self-hosted self-hostable aggregator FreshRSS, it doesn't work: https://rss.skraynov.ru/i/?a=normal&get=f_6

**Comment by archon810** [comment]
@1nikolas I'm looking into the issues with Feedly images. They're using some scraper reporting itself as a really old version of Chrome (Chrome 23). I'm waiting for a new post to get published to see if the issue is resolved.

**Comment by archon810** [comment]
@slavakraynov Check now please.

**Comment by slavakraynov** [comment]
> @slavakraynov Check now please.

It works, thank you

**Comment by 1nikolas** [comment]
> @1nikolas I'm looking into the issues with Feedly images. They're using some scraper reporting itself as a really old version of Chrome (Chrome 23). I'm waiting for a new post to get published to see if the issue is resolved.

It seems like its working now. Thanks

![Monosnap 2020-07-27 3 PM-21-41](https://user-images.githubusercontent.com/30593419/88541177-fcf81580-d01c-11ea-9c0b-d3d289604ce5.png)
![Monosnap 2020-07-27 3 PM-21-58](https://user-images.githubusercontent.com/30593419/88541193-02edf680-d01d-11ea-9981-3905f5112431.png)

**Comment by PerfectSlayer** [comment]
Hello @archon810 

Like @slavakraynov I'm using a self hosted RSS reader based on [Tiny Tiny RSS](https://tt-rss.org/).
It is possible to whitelist it? (if you need any more details about it, please ask 😉 )

Thanks a lot!

**Comment by archon810** [comment]
@PerfectSlayer TinyTinyRSS should be working. Is it not for you?

**Comment by PerfectSlayer** [comment]
Negative, it is not.

**Comment by archon810** [comment]
OK, that's odd. Which feed are you using, do you know which IP is running the queries, and can you post the full contents of the feed in a gist?

**Comment by PerfectSlayer** [comment]
I am using this feed: https://www.androidpolice.com/feed/ and the IP should be this one: `213.186.33.3`.

I found that I use [FeedIron plugin](https://github.com/feediron/ttrss_plugin-feediron) for TinyTinyRSS. It grabs the content from the article URL and clean it for the RSS reader. I am investigating its source code to check if it uses the TinyTinyRSS user-agent or a default one.

If the filtering based on User-Agent? If yes, is `Tiny Tiny RSS/UNKNOWN (Unsupported) (http://tt-rss.org/)` allowed?

**Comment by archon810** [comment]
I see you're using OVH... you can see why OVH is blocked now https://www.abuseipdb.com/check/213.186.33.3.

Regardless, I don't see any requests from that IP address.

Tiny Tiny RSS is permitted to grab the feeds, but if you're trying to then load the actual web pages and manipulate the content, you will fail (from OVH and other spam-filled hosts).

**Comment by PerfectSlayer** [comment]
Ok, thanks for all the details!

It's your site and feed and you try to protect it. I choose OVH at the time to support a local product (at least from my country). I will setup an HTTP proxy on another server to mirror your feed so my reader can grab it.

Thanks for your help and sorry for the trouble.

**Comment by moneytoo** [comment]
I noticed issues with my own RSS reader. However the bigger issue is that I actually have a commercial app that needs to fetch any url (article on Android Police) and parse Open Graph data (title, description, image, video etc.) to allow users see its preview when sharing in that app. It's not on OVH but other big providers in Europe (Online.net, Hetzner.de, including privately owned IP ranges).

**Comment by archon810** [comment]
These providers have way too much scam activity going on, unfortunately, so we will not be able to unblock them and they will continue to get challenges such as captchas.
