### ISSUE TITLE
Parsing RSS feed not working

### ISSUE THREAD

**Issue by kvizcarra** [android-police/androidpolice-public#123]
#### Expected behavior
Full article is parsed by [FeedMe Android app](https://play.google.com/store/apps/details?id=com.seazon.feedme)  or Feedbin parser.

#### Actual behavior
403 Forbidden or null is shown when parsed with these services
![Screenshot_20200730-132927_FeedMe](https://user-images.githubusercontent.com/25014586/88972269-235ec080-d26a-11ea-91c9-d59c05288a6a.png)
![Screenshot_20200730-132947_FeedMe](https://user-images.githubusercontent.com/25014586/88972281-28bc0b00-d26a-11ea-9b16-450262affad3.png)

#### Steps to reproduce the problem
1. Download [FeedMe](https://play.google.com/store/apps/details?id=com.seazon.feedme) and log into a Feedly account that is subscribed to AndroidPolice
1. Tap an article from AndroidPolice
1. Tap 3-dot menu > "Reload page"  > "Feedbin Parser" or "FeedMe"

**Comment by archon810** [comment]
Please check now for `Feedbin`.

For `FeedMe`, do you know the user agent they use? I can't seem to find FeedMe, feedme, or Feedme hitting our servers and getting blocked.

**Comment by archon810** [comment]
I emailed FeedMe FWIW.

**Comment by kvizcarra** [comment]
Still the same "null" error
[Screenshot_20200730-185627_FeedMe](https://user-images.githubusercontent.com/25014586/88991817-8cf4c400-d296-11ea-8959-e6347eade426.png)

Hopefully @seazon has some insight

**Comment by archon810** [comment]
As I said, I fixed `Feedbin`, not `FeedMe`.

**Comment by seazon** [comment]
@archon810 `okhttp/4.7.2` the user-agent which used for FeedMe mobilizer.
<img width="749" alt="Screen Shot 2020-08-02 at 8 14 02 AM" src="https://user-images.githubusercontent.com/2791800/89112635-22ab7180-d498-11ea-8337-82621c498b5f.png">
<img width="556" alt="Screen Shot 2020-08-02 at 8 14 51 AM" src="https://user-images.githubusercontent.com/2791800/89112643-3f47a980-d498-11ea-8543-4012d76b07da.png">

**Comment by archon810** [comment]
@seazon Sorry, generic library user-agents like https://square.github.io/okhttp/ will not be approved. It's not a good idea to use the default library UA, you should be overriding it with one specific to your application.

**Comment by archon810** [comment]
Much better 👍.
