### ISSUE TITLE
Comments time is incorrect

### ISSUE THREAD

**Issue by Waqas334** [android-police/androidpolice-public#126]
I just saw an article [link at bottom] which is published around 36 minutes ago and it got 60 comments. When I looked at the comment, it was clearly written on top 1month ago. Please check.

Article link: https://www.androidpolice.com/2020/09/05/samsung-internet-vs-google-chrome-should-you-switch/#disqus_thread

**Comment by archon810** [comment]
Look at the top: "This story was originally published on Jul 25, 2020 and last updated 42 minutes ago."
