### ISSUE TITLE
Disqus comments not posting on AP, but do elsewhere.

### ISSUE THREAD

**Issue by T4rded** [android-police/androidpolice-public#128]
#### Expected behavior

I enter a Disqus comment for other people to see and respond to and I can have conversations with them.

#### Actual behavior

No one sees comments that I post on AP and upon viewing articles in privacy mode or other browsers, I cannot see my own comments until I log into Disqus.

#### Steps to reproduce the problem

Made several comments across several AP articles for months and get no responses or acknowledgements.  Other sites post my comments just fine and I can correspond with people elsewhere.  I have also posted from several different devices and networks.

####Comment

Disqus name is "T4rd".  I'm not sure if shadow banning is a thing, but that's essentially what it seems like.

**Comment by archon810** [comment]
You have indeed been shadowbanned several months ago for this absolutely inappropriate comment:

> "I love genitals like mine in my mouth, celebrate meeeeeee!"
> 
> Honestly never got the "pride" aspect of your sexual preference. I couldn't care less if your straight or whatever else and think most companies jumping on this train are solely doing it for the PR and also out of fear of persecution from the liberal attack mob that's always looking for their next witch hunt and thing to get canceled.

Given your other generally positive for the community commenting history, I am making a decision to reverse this ban, but you're definitely on thin ice with the mod team, so please stay civil and respectful.
