### ISSUE TITLE
Change Consent, Legitimate interest, Opt-Out options revert to opt-in across multiple vendors after submit

### ISSUE THREAD

**Issue by dataexpatoptout** [android-police/androidpolice-public#135]
#### Expected behavior
Change Preferences, Vendor Options, toggle Legitimate interest - Opt-Out limit tracking to off, submit preferences

#### Actual behavior
Legitimate interest toggles back to ON across all settings changed

#### Steps to reproduce the problem
Attempt to Opt-Out and limit tracking, effort is blocked and not recognized through privacy settings made.

**Comment by archon810** [comment]
We've moved to using Google Funding Choices for the CMP earlier this year. This is Google's own solution, and if something doesn't work, it's likely either an issue on their side or the way they've designed the CMP. I think the issue you're talking about is related to the latter - they reset the preferences when you attempt to modify them (which I've reported to them in the past). There's nothing we can do from our end, from what I can tell.
