### ISSUE TITLE
Link comment stuck on pending

### ISSUE THREAD

**Issue by afk789** [android-police/androidpolice-public#139]
![Screenshot (310)](https://user-images.githubusercontent.com/59767288/116561080-d4a48c80-a8b6-11eb-9eb6-862e2035782e.png)
#### Expected behavior
I expected my link comment would have been approved easily since it's related to the topic.

#### Actual behavior
Now it's stuck on pending for 2 days now.

**Comment by archon810** [comment]
I had Taylor take a look and sort this out. Sorry about the delay.
