### ISSUE TITLE
text stays dark when using dark mode Windows edge

### ISSUE THREAD

**Issue by yuboq** [android-police/androidpolice-public#141]
#### Expected behavior
Text is supposed to contrast background color

#### Actual behavior
Text remains black and blends into background

#### Steps to reproduce the problem

1.  open Windows edge. 
2.  change appearance to dark theme (overflow menu -> settings -> appearance -> dark)
2.  go to [this webpage](https://www.androidpolice.com/2018/04/28/make-sense-buy-last-years-smartphone/)

<img width="1043" alt="delete" src="https://user-images.githubusercontent.com/3803438/127173849-7a601b54-0991-42c3-8792-3f4ad75af0d7.PNG">

**Comment by archon810** [comment]
The issue was limited to this one post, it seems. There was CSS present that overrode our dark theme colors. I've removed the offending CSS, and the post looks good in dark mode now.

Thanks for reporting.
