### ISSUE TITLE
No HTTPS support

### ISSUE THREAD

**Issue by zanedb** [android-police/androidpolice-public#83]
#### Expected behavior
The website should have HTTPS support.

#### Actual behavior
It doesn't. HTTPS is a critical security feature that is necessary, especially for [login pages](http://www.androidpolice.com/wp-login.php). Also, a malicious user on someone's network or their ISP can view exactly what they read on AP and target them specifically. Not to mention the form data on your site. This is a HUGE security flaw, and has a very easy fix, called [Certbot](https://certbot.eff.org/).

#### Steps to reproduce the problem
Try visiting [the website with HTTPS](https://www.androidpolice.com). It redirects to HTTP, and doesn't support HTTPS.

Thank you for your time.

**Comment by archon810** [comment]
We'll be rolling out https by the end of the year. It's almost ready to go. I'll leave this ticket open.

**Comment by zanedb** [comment]
Great, thanks!

**Comment by rmjones2006** [comment]
Any update on this?

**Comment by archon810** [comment]
Not yet, unfortunately. I lost some developers, and my focus right now is on some backend apkmirror features.

**Comment by Nedlinin** [comment]
@archon810 : Out of curiosity, what is the road map for it?  It seems like it'd be fairly easy to put an nginx server in place acting as an SSL termination point and reverse proxy requests to whatever your current setup is.  Takes very little backend change while also allowing SSL for end users.

**Comment by archon810** [comment]
Released.

https://plus.google.com/u/0/+ArtemRussakovskii/posts/WqN6q6wEzKU
