### ISSUE TITLE
Malicious ad

### ISSUE THREAD

**Issue by ScorchConway** [android-police/androidpolice-public#87]
#### Expected behavior
No malicious ads

#### Actual behavior
On October 30, I touched an ad to scroll, and before I lifted my finger I was sent to a page with a popup saying 'your Android was hacked yadda yadda...'

Link:
Firefox support for web-based Google Earth is in development
https://search.app.goo.gl/37y5

**Comment by archon810** [comment]
Please take a look at https://plus.google.com/+ArtemRussakovskii/posts/56BYLha71bX.

If we ever get a resolution here, I'll update this ticket.

**Comment by steronydh** [comment]
Sorry I don't remember the articles but I've had a couple of these recently browsing AP articles in Feedly.

**Comment by archon810** [comment]
We haven't had reports of such behavior in a while, so I'm going to close this. Chrome has also gotten better at preventing such popups and redirects, and perhaps ad networks got better at identifying such hijackings as well.
