### ISSUE TITLE
Ads are causing page to lock up and use tons of memory

### ISSUE THREAD

**Issue by Volodesi** [android-police/androidpolice-public#90]
Sometimes when visiting any page on Android Police, the memory usage will skyrocket and cause the tab to become unresponsive. 

I ended up having to turn AdBlock back on just to browse the site. I completely closed Chrome and only opened a Android Police Tab to test this.

Edit: Also seems to be happening with AdBlocker on as well. The CPU usage goes to about 45-90% and RAM usage just goes up and up without stopping. I hit as high as 8 GB of RAM usage if I left it sitting there.

![image](https://user-images.githubusercontent.com/36998033/36952495-8d820858-1fd6-11e8-87e8-0fb1f2b72c62.png)

Seems to be from 
![image](https://user-images.githubusercontent.com/36998033/36952446-dff09dbc-1fd5-11e8-88aa-f27685e32f23.png)

![image](https://user-images.githubusercontent.com/36998033/36949731-ee1a866a-1fb1-11e8-8a9c-3b8d358f6f31.png)

**Comment by archon810** [comment]
Unfortunately, there's not much we can do until Google and other ad networks (but we mostly use Google) prohibits runaway scripts like that and gives us the ability to block video ads. I've written extensively about crap like this, but we're powerless if even Google's own ad network allows ads to misbehave this way.

Please see:

- https://plus.google.com/+ArtemRussakovskii/posts/53n5LdCYTbF (and https://news.ycombinator.com/item?id=15145226)
- https://plus.google.com/u/0/+ArtemRussakovskii/posts/7jMWV7oCQpn
- https://plus.google.com/+ArtemRussakovskii/posts/VgrLdYcoifr

**Comment by Volodesi** [comment]
Does contributing disable ads completely?

Cause, if not. That would be kind of pointless. I am still getting run away's with AdBlock Plus going.

**Comment by archon810** [comment]
No, right now contributing just lets you donate some $$$ if you feel bad for using ad blockers.

**Comment by archon810** [comment]
I'm going to close this as it's more of an AdSense and other networks issue than a technical issue with the site.
