### ISSUE TITLE
Random crashes of Android Pie and apps on Android Pie

### ISSUE THREAD

**Issue by Senamun** [android-police/androidpolice-public#93]
I'm on a Pixel 2 XL. I've upgraded from the Android P beta program. Already during the beta's I experienced random crashes of Android and also randomly on apps. This can be any app. Restarting Android fixes the problem. When not restarting the affected app seems to stabilize after some time. I've had this with various Google apps but also with 3rd party apps. For example Wordfeud, KLM app, ING banking app, Swiftkey, Facebook Messenger etc. I did not have this problem on Android Oreo. It started when entering Android P beta. I had hoped it would be fine with the final Pie update but unfortunately no. I have not tried to do a factory reset because it's so much work to get everything back as I want it.

Is this a known issue?

**Comment by archon810** [comment]
I'm sorry but this is not the right forum for such issues.

**Comment by Senamun** [comment]
I'm sorry
