### ISSUE TITLE
Tapatalk plug in??

### ISSUE THREAD

**Issue by techinv** [android-police/androidpolice-public#94]

**Comment by techinv** [comment]
According to Tapatalk support, the plug in so that Android Police can be published on Tapatalk is disabled.  Is it possible to put this back in place again?

**Comment by archon810** [comment]
Hi,

I'm not aware of any Tapatalk plugins on AP in the past, or what Tapatalk integration would achieve anyway. Isn't Tapatalk for browsing forums?

**Comment by techinv** [comment]
Artem,

Thanks for the quick reply. Yes, Tapatalk is for viewing forums. Here is
the response that I received from one of their support people about why I
can't view AP content on Tapatalk anymore.

Thank you for the update. This forum doesn't use Tapatalk anymore. In order
to be published on Tapatalk, site owner/admin will need to install the
Tapatalk plugin on their site. You can contact the forum admin for the
request to put it back to the app. Requests from members are looked into
more quickly.
Show quoted text
-- 
Thanks,
Jocelyn

**Comment by archon810** [comment]
I still don't understand what exactly you were viewing before that you can't now. AP doesn't have forums and never had them. We never had a Tapatalk plugin.

**Comment by techinv** [comment]
Hi Artem:

I used to be able to see articles from AP via Tapatalk app on my phone.
That is not working now.  Here is a further update from Tapatalk support
about this issue.

*Right, both of them are RSS feed integrated in the app which is no longer
supported. The forum owner has to install the Tapatalk plug-in at their
forum to be able to add RSS feed for it to continue to work. You can send
your request to the forum admin to add Tapatalk. *

**Comment by archon810** [comment]
AP supports all the standard Wordpress RSS feeds, which Tapatalk is free to use.

Again, we never had a Tapatalk plugin, and there are no plans to add it.
