### ISSUE TITLE
"We value your privacy" wall blocks reading privacy policy

### ISSUE THREAD

**Issue by gunnarcodes** [android-police/androidpolice-public#95]
#### Expected behavior
I would have liked to read:

https://www.androidpolice.com/androidpolice-com-privacy-policy/

There is a link to the page in the "We value your privacy" wall.

#### Actual behavior

The page loads, but then the "We value your privacy" wall appears over it, blocking me from reading it.

#### Steps to reproduce the problem
(on mobile), load
https://www.androidpolice.com/androidpolice-com-privacy-policy/
before accepting cookies

Click link "Find out more by reading our cookie and privacy policies"

**Comment by archon810** [comment]
Thanks for reporting this. I'll look into fixing this behavior as you're right that we have a chicken/egg problem.

![image](https://user-images.githubusercontent.com/469543/52661356-b3fae280-2eb6-11e9-8eb4-10ab484b25fc.png)

**Comment by FilipeOS** [comment]
The privacy settings button (blue button) hides the TIP US popup SEND button too.

**Comment by archon810** [comment]
@FilipeOS Are you talking about this second button that shows up in the modal? I can't seem to reproduce the two buttons being overlaid, but there's really no reason for that second button to show up inside the modal in the first place, so we have to fix that.

![image](https://user-images.githubusercontent.com/469543/54048058-86d7e200-418d-11e9-9cff-2e5272d710a3.png)

**Comment by FilipeOS** [comment]
@archon810 Yes but on my 24"display it shows the SEND under Privacy settings and I can't reach it, only by pressing ENTER and submitting form

**Comment by archon810** [comment]
Both the Tip Us iframe and the privacy policy page no longer have the CMP in them.
