### ISSUE TITLE
Breaking News Button incorrectly placed

### ISSUE THREAD

**Issue by Silver-Fullbuster** [android-police/androidpolice-public#96]
#### Expected behavior
Breaking news button should show up along the width of the page

#### Actual behavior
The breaking news button is shifted towards the right of the website page, making it barely visible and allowing the browser to scroll horizontally further than the page itself

#### Steps to reproduce the problem

Visit the site when a breaking news is present

Browser: Firefox v66.0.5
OS: Windows 1809 (17763.503)

![Screenshot](https://i.imgur.com/XWepEkW.png)

**Comment by archon810** [comment]
Thanks for the report. It seems to be a Firefox-only bug. We have a fix in the works.

**Comment by archon810** [comment]
A fix has been rolled out, thank you again for reporting it.
