### ISSUE TITLE
You still have a Google+ share button (that doesn't work)

### ISSUE THREAD

**Issue by MisterSpak** [android-police/androidpolice-public#97]
![Screenshot_20190520-130422_Chrome](https://user-images.githubusercontent.com/12399661/58048676-f2301f80-7aff-11e9-88f7-73e1977ecf0f.jpg)
https://www.androidpolice.com/2019/04/02/google-dies-today-by-the-hand-of-googles-apathy/

**Comment by archon810** [comment]
Hi,

Indeed, this button will be phased out soon in favor of an entirely new AddThis-based widget system. We hope to have it available soon.

**Comment by archon810** [comment]
We've rolled out a new social solution based on addthis.com.

Unfortunately, it's blocked by ad blockers, so you may not see it at all. But the old buttons are gone.
