### ISSUE TITLE
Titles of article in Pocket are fetching the incorrect info

### ISSUE THREAD

**Issue by ptrmaruchinsu** [android-police/androidpolice-public#99]
#### Expected behavior
Should list title of article as is

#### Actual behavior
for your Free and on-sale apps and games the title is listing "XX temporarily free and YY on-sale apps and games for the weekend"

#### Steps to reproduce the problem
Subscribe in IFTTT to your http://feeds.feedburner.com/AndroidPolice

**Comment by archon810** [comment]
This happened because the story went live with the wrong title, and apparently Pocket or IFTTT don't get updates to stories, which is something outside of our control.

I have talked to the author to make sure it doesn't happen again.
